<?php

namespace App\StdLib;

use App\Interpreter;
use App\LoxFunction;
use App\LoxInstance;

class StdClassMethod extends LoxFunction
{
    private $callable;
    private $arity;

    /**
     * @inheritDoc
     */
    public function __construct(callable $fn, int $arity)
    {
        parent::__construct(null, null, false);
        $this->callable = $fn;
        $this->arity = $arity;
    }

    public function bind(LoxInstance $instance)
    {
        return $this;
    }

    public function arity(): int
    {
        return $this->arity;
    }

    public function call(Interpreter $interpreter, array $arguments)
    {
        return call_user_func_array($this->callable, $arguments);
    }

    public function __toString(): string
    {
        return parent::__toString(); // TODO: Change the autogenerated stub
    }


}